name: PyTest CI for Backend

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup code
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Setting up Python Environment
        working-directory: ./Backend/
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      
      - name: Run all tests
        run: pytest --verbose
