name: Vitest CI for Frontend

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Execute Tests
        run: npm run test